{% set version = "1.3.0" %}

package:
  name: yasm
  version: {{ version }}

source:
  fn: yasm-{{ version }}.tar.gz
  url: http://www.tortall.net/projects/yasm/releases/yasm-{{ version }}.tar.gz
  sha1: b7574e9f0826bedef975d64d3825f75fbaeef55e

build:
  skip: True  # [win and vc != 14]
  number: 2
  # we only build with vc14 on win.  Since there are no shared libraries, we just need to ensure the right runtime,
  #    not line up shared libs
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [not win]
  run:
    - vs2015_runtime   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libyasm.a              # [unix]
    - if not exist %LIBRARY_LIB%\\yasm.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\yasm.dll exit 1  # [win]
    - vsyasm --help
    - yasm --help
    - ytasm /h
    - yasm --version

about:
  home: http://www.tortall.net/projects/yasm/
  license: BSD 3-Clause
  summary: 'Yasm is a complete rewrite of the NASM assembler under the "new" BSD License.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
