# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d2f0v8B3i2GG7c+wgAOTHtWcS+if84qWil0r/40TwrKDyKunGwN0WtteocjwzLfW5a8JqhsopYZxBzDaxm+tT7tLp5I1fqSEYHHXVD49AG+E2iFblcze7NK4l4HqlypRHUgNGDVzFL/CnOwtCmWK3qeYEDjebjGULl37Rz+0I4pkN1IK/SNJ8tQhcTLDykAJpEey4zjhIoTDnKiAHvBXn1D3pMEp5s7HBlc0n0S/u4EuZGiIhmkqWlivgULt6oE5BmZIWheTide3Us1fItylaIuRXZcv+eALCgJZs0ytwb+IB8kFJvoKduvvKa1+BV2TbfuP/8GwOW9vcYWiepqRg3Yx72Hw0OmzUDIIG+KFQ/6K0TQSZGZV8loPDjXRJOkH99NLMj+7b9iak+DQ086gGaUVXQsU7hO+KcnlV+CXJJDHpTg+4ow+yhO6OuifA020mhxtA4kSLY/vd860lSIcOPoMzNAWuIijJClZwuZdX/dspoLjR9kV2EMYlzQGs+jW0glEhmOW11GmpHgqKTDPfiYkS9ZpG6DnRXvUAPHAhbAwCzKiZ96FwlqsfZenGQ4BjupSM48+iPJs+hMUH32tOIY9IlflHQQg2n8QbGQpAxe/lhpjZ1nWB8GBi+IwlJrH+r3uu5BEj5KKSt8ZnnMhJlm5GcU0FbamHTgwxdrwcyE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
